apiVersion: v1
kind: ConfigMap

metadata:
  name: web-content
  namespace: k8s-foundations

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes Project</title>
    </head>

    <body>
      <h1>Hello from Kubernetes!</h1>
      <p>My first Kubernetes Deployment is working.</p>
    </body>
    </html>