apiVersion: v1
kind: Service

metadata:
  name: web-service
  namespace: k8s-foundations

spec:

  # Find Pods with this label
  selector:
    app: web-app

  ports:

    - protocol: TCP

      # Service listens on port 80
      port: 80

      # Traffic gets forwarded to port 80 in the container
      targetPort: 80

  # Makes the service reachable through a node port
  type: NodePort